[package]
name = "file_appender"
version = "0.1.0"
edition = "2021"
description = "easy way to concat a directory into a single file"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.6"
walkdir = "2.3.3"
